<?php

namespace HB\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends EntityRepository
{
    
    public function getSelectList()
    {
        $qb = $this->createQueryBuilder('u')
                ->orderBy('u.dateCreation', 'DESC');
        return $qb;
    }
}
